### ISSUE TITLE
I think the term "Inspired workshops" needs review

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/test#2]
I do have an issue with 'inspired workshops' as a term as it has more than one meaning. The first meaning of 'inspired' that springs to mind is probably this: 'to exert an animating, enlivening, or exalting influence'. 

Obviously *we* mean that the inspired workshops were based on Library Carpentry lessons but do not fit the 'official' definition for those, but a cursory reading might be that people think some workshops were 'inspired' rather than 'inspired by ...' and then what does that mean for the rest - that they were rather uninspired???
I really think we need to find a better term.

**Comment by libcce** [comment]
Alternatively, we can use Library Carpentry-based workshops, similar to what they did at TIB Hannover https://tibhannover.github.io/2018-07-09-FAIR-Data-and-Software/. However, I believe we settled on 1-day, 2-day, multi-day workshops which is even better IMHO. There are three pages where this is the case, About Us, Our Workshops, and Get Involved. The "inspired workshops" will be removed from the navigation and it will just be upcoming workshops.

**Comment by libcce** [comment]
The 'inspired' language has been removed. Thanks for the suggestion!
